### ISSUE TITLE
Erreur de redirection

### ISSUE THREAD

**Issue by LoicXIII** [LoicXIII/Springboot_tds#2]
Je ne comprend pas, je veux uniquement faire en sorte que lorsque l'on ajoute index dans l'URL, on soit envoyé vers le template index, cependant ce code génère une erreur

https://github.com/LoicXIII/Springboot_tds/blob/aeae25378144d15bed99fa2ce27368b3f01adc99/src/main/java/com/example/tp5/controller/UserController.java#L6-L15

ping @jcheron

**Comment by jcheron** [comment]
C'est une devinette ?
Quelle erreur ?

**Comment by LoicXIII** [comment]
oups, j'ai oublié de vous la montrer
![image](https://user-images.githubusercontent.com/50839091/77924873-892f4180-72a4-11ea-91b2-56d3db2d38f8.png)

**Comment by jcheron** [comment]
C'est normal que `application.properties` soit vide ?
https://github.com/LoicXIII/Springboot_tds/blob/aeae25378144d15bed99fa2ce27368b3f01adc99/src/main/resources/application.properties#L1

**Comment by LoicXIII** [comment]
Oui il semble que le problème venait de là, désolé pour ce dérangement
