### ISSUE TITLE
la déconnexion est correcte ?

### ISSUE THREAD

**Issue by LoicXIII** [LoicXIII/Springboot_tds#3]
Je voulais savoir si pour la déconnexion, pour vider la variable de session, ce code est correct

https://github.com/LoicXIII/Springboot_tds/blob/088f990bd23907f4a1cf7a590f94f3362f60509b/src/main/java/com/example/tp5/controller/UserController.java#L45-L50

sachant que je l'initialise ainsi
https://github.com/LoicXIII/Springboot_tds/blob/088f990bd23907f4a1cf7a590f94f3362f60509b/src/main/java/com/example/tp5/controller/UserController.java#L33-L43

ping @jcheron

**Comment by LoicXIII** [comment]
finalement j'ai trouvé, c'est bon

**Comment by jcheron** [comment]
> Je voulais savoir si pour la déconnexion, pour vider la variable de session, ce code est correct
 https://github.com/LoicXIII/Springboot_tds/blob/088f990bd23907f4a1cf7a590f94f3362f60509b/src/main/java/com/example/tp5/controller/UserController.java#L45-L50

La réponse est non, vous ne fermez pas la session là, vous supprimez juste une variable...
Il faut appeler la méthode `invalidate()` sur l'objet `HttpSession`
