### ISSUE TITLE
Formulaire création script

### ISSUE THREAD

**Issue by LoicXIII** [LoicXIII/Springboot_tds#4]
Bonjour, je rencontre un problème : 
lorsque l'on rempli le formulaire et qu'on clique sur le bouton créer, j'aimerai que l'action scriptSubmit se fasse dans le controleur, au lieu de sa, je me retrouve avec un url étrange, comment bien faire un formulaire ?
![image](https://user-images.githubusercontent.com/50839091/78451721-9d4db700-7687-11ea-9629-87a8647d8baf.png)

https://github.com/LoicXIII/Springboot_tds/blob/dbd481e5cdeebacdf51071e1c9f7eebf8ac981e5/src/main/resources/templates/scriptNew.html#L15-L23

https://github.com/LoicXIII/Springboot_tds/blob/dbd481e5cdeebacdf51071e1c9f7eebf8ac981e5/src/main/java/com/example/tp5/controller/ScriptController.java#L29-L34

ping @jcheron

**Comment by jcheron** [comment]
Vous utilisez du `mustache` et non du `Thymeleaf` comme moteur de template, donc enlevez les balises `th:..`
mettez des attributs `name` sur vos champs du formulaire...
Et des `textarea` pour les champs text de grande taille.

```html
     <form action="/script/submit" method="post"> 
         Titre : <input type="text" name='title'> 
         Description <textarea name='description'></textarea> 
         content <textarea name='content'></textarea> 
         date de création <input type="date" name='date'> 
         <button type="submit">Créer</button> 
     </form> 
```

**Comment by LoicXIII** [comment]
merci !
